### ISSUE TITLE
update ur socket.io-client 

### ISSUE THREAD

**Issue by julianfrank** [stbrenner/socket.io-proxy#14]
UR code does not work as-is right now... The Reason is that u are using the 0.9 version of socket io which is not compatible with the current 2.0 version of socketio....Just bump ur version to 2.x and ur code works flawlessly....

**Comment by stbrenner** [comment]
Thanks. I'll update it soon.

**Comment by xnnkmd** [comment]
Any update?

**Comment by chrishatherall** [comment]
@stbrenner Hi Stephan, any chance of getting this version updated soon?

**Comment by drprime** [comment]
are it working now?

**Comment by TheFireBlast1** [comment]
This still isn't working.
@stbrenner when will you be able to update this?
